baseurl = "/"
relativeurls = true
languageCode = "en-us"
title = "Camila Ferreira"
theme = "hugo-theme-bleak"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/camilapferreira"
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/pferreiracamila"
[[menu.main]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/camilapferreira/"


[params]
    description = "Sharing experiences that matter."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"
    
    googleAnalyticsUserID = "UA-101477183-1"
    
    cover = "http://cdn.playbuzz.com/cdn/0c3fd0fb-937a-46f3-b181-109bde091100/82e92498-5844-4701-9fd8-ebf3fe4a5f81.jpg"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

    [params.logo]
    url = "/img/logo_icon.png"
    width = 50
    height = 50
    alt = "Camila"
    
